package kz.whosnext.hr.candidate.model.enums;

public enum ActivityAction {

    VACANCY_CREATED,
    VACANCY_UPDATED,
    VACANCY_DEACTIVATED,
    VACANCY_ACTIVATED,

    APPLICATION_SUBMITTED,
    APPLICATION_UPDATED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_REVISION_REQUESTED,
    APPLICATION_PROMOTED,

    CANDIDATE_PROFILE_UPDATED,

    POSITION_CREATED,
    POSITION_UPDATED,
    POSITION_DELETED,
    CONTRACT_TYPE_CREATED,
    CONTRACT_TYPE_UPDATED,
    CONTRACT_TYPE_DELETED
}
