package kz.whosnext.hr.auth.model.enums;

public enum ActivityAction {

    USER_REGISTERED,
    USER_EMAIL_CONFIRMED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_PROFILE_UPDATED,
    USER_PHOTO_UPLOADED,
    USER_PASSWORD_CHANGED,
    USER_PASSWORD_RESET_REQUESTED,
    USER_PASSWORD_RESET,
    USER_ROLE_CHANGED,
    USER_DELETED,
    USER_TOKEN_REFRESHED,

    VACANCY_CREATED,
    VACANCY_UPDATED,
    VACANCY_DEACTIVATED,
    VACANCY_ACTIVATED,

    APPLICATION_SUBMITTED,
    APPLICATION_UPDATED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_REVISION_REQUESTED,
    APPLICATION_PROMOTED,

    CANDIDATE_PROFILE_UPDATED,

    POSITION_CREATED,
    POSITION_UPDATED,
    POSITION_DELETED,
    CONTRACT_TYPE_CREATED,
    CONTRACT_TYPE_UPDATED,
    CONTRACT_TYPE_DELETED,

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DISMISSED,

    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,

    EMP_POSITION_CREATED,
    EMP_POSITION_UPDATED,
    EMP_POSITION_DELETED,

    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,

    ATTENDANCE_MARKED,
    ATTENDANCE_RECORD_DELETED,
    ATTENDANCE_CHECK_IN,
    ATTENDANCE_CHECK_OUT,

    TIME_ENTRY_SAVED,

    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    DOCUMENT_GENERATED,
    DOCUMENT_SIGNED,
    DOCUMENT_REGENERATED,

    TEMPLATE_UPLOADED,
    TEMPLATE_UPDATED,
    TEMPLATE_DELETED,

    CERTIFICATE_REQUESTED,
    CERTIFICATE_COMPLETED,
    CERTIFICATE_REJECTED,
    CERTIFICATE_GENERATED,

    DOCUMENT_REQUEST_CREATED,
    DOCUMENT_REQUEST_STATUS_UPDATED,
    DOCUMENT_REQUEST_SIGNED,

    NEWS_CREATED,
    NEWS_UPDATED,
    NEWS_DELETED,

    WORK_SCHEDULE_CREATED,
    WORK_SCHEDULE_UPDATED,
    WORK_SCHEDULE_DELETED,

    PAYROLL_PROFILE_UPSERTED,
    PAYROLL_CALCULATED,
    HOLIDAY_CREATED
}
