package kz.whosnext.hr.employeeservice.model.enums;

public enum ActivityAction {

    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DISMISSED,

    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,

    EMP_POSITION_CREATED,
    EMP_POSITION_UPDATED,
    EMP_POSITION_DELETED,

    LEAVE_REQUESTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,

    ATTENDANCE_MARKED,
    ATTENDANCE_RECORD_DELETED,
    ATTENDANCE_CHECK_IN,
    ATTENDANCE_CHECK_OUT,

    TIME_ENTRY_SAVED,

    DOCUMENT_REQUEST_CREATED,
    DOCUMENT_REQUEST_STATUS_UPDATED,
    DOCUMENT_REQUEST_SIGNED,

    CERTIFICATE_REQUESTED,
    CERTIFICATE_COMPLETED,
    CERTIFICATE_REJECTED,

    NEWS_CREATED,
    NEWS_UPDATED,
    NEWS_DELETED,

    WORK_SCHEDULE_CREATED,
    WORK_SCHEDULE_UPDATED,
    WORK_SCHEDULE_DELETED,

    PAYROLL_PROFILE_UPSERTED,
    PAYROLL_CALCULATED,
    HOLIDAY_CREATED
}
