package kz.whosnext.hr.employeeservice.service;

import kz.whosnext.hr.employeeservice.exception.BadRequestException;
import kz.whosnext.hr.employeeservice.exception.ResourceNotFoundException;
import kz.whosnext.hr.employeeservice.mapper.DocumentRequestMapper;
import kz.whosnext.hr.employeeservice.model.dto.request.CreateDocumentRequestDto;
import kz.whosnext.hr.employeeservice.model.dto.request.UpdateDocumentRequestStatusDto;
import kz.whosnext.hr.employeeservice.model.dto.response.DocumentRequestResponse;
import kz.whosnext.hr.employeeservice.model.entity.DocumentRequest;
import kz.whosnext.hr.employeeservice.model.entity.Employee;
import kz.whosnext.hr.employeeservice.model.enums.DocumentRequestStatus;
import kz.whosnext.hr.employeeservice.model.enums.DocumentRequestType;
import kz.whosnext.hr.employeeservice.model.enums.NotificationType;
import kz.whosnext.hr.employeeservice.model.enums.ActivityAction;
import kz.whosnext.hr.employeeservice.model.enums.ActivitySource;
import kz.whosnext.hr.employeeservice.repository.DocumentRequestRepository;
import kz.whosnext.hr.employeeservice.repository.EmployeeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class DocumentRequestService {

    private final DocumentRequestRepository documentRequestRepository;
    private final EmployeeRepository employeeRepository;
    private final NotificationService notificationService;
    private final DocumentRequestMapper documentRequestMapper;
    private final ActivityLogProducer activityLogProducer;

    @Transactional
    public DocumentRequestResponse create(UUID userId, String actorEmail, String actorRole, CreateDocumentRequestDto req) {
        Employee employee = employeeRepository.findByUserId(userId)
                .orElseThrow(() -> new ResourceNotFoundException("Сотрудник не найден по userId: " + userId));

        DocumentRequestType type = DocumentRequestType.valueOf(req.documentType());
        // OTHER requires HR processing; all other types are auto-generated on the client and fulfilled immediately
        boolean autoGenerated = type != DocumentRequestType.OTHER;

        DocumentRequest dr = DocumentRequest.builder()
                .employee(employee)
                .documentType(type)
                .comment(req.comment())
                .status(autoGenerated ? DocumentRequestStatus.DONE : DocumentRequestStatus.PENDING)
                .build();

        dr = documentRequestRepository.save(dr);
        log.info("Заявка на документ создана: id={}, type={}, employeeId={}, status={}", dr.getId(), type, employee.getId(), dr.getStatus());

        activityLogProducer.log(
                ActivityAction.DOCUMENT_REQUEST_CREATED, ActivitySource.EMPLOYEE_SERVICE,
                userId, actorEmail, actorRole,
                "DocumentRequest", dr.getId().toString(),
                "Document request created: " + type);

        if (autoGenerated) {
            // Notify the employee that their EDS-signed document is ready
            notificationService.createByEmployeeId(employee.getId(),
                    "Документ готов",
                    "Ваша справка «" + type.name() + "» подписана ЭЦП и доступна для скачивания",
                    NotificationType.GENERAL, dr.getId(), "DOCUMENT_REQUEST");
        } else {
            // Only OTHER type requests need HR involvement
            notifyHr(employee, dr);
        }

        return documentRequestMapper.toResponse(dr);
    }

    @Transactional(readOnly = true)
    public Page<DocumentRequestResponse> getMyRequests(UUID userId, Pageable pageable) {
        Employee employee = employeeRepository.findByUserId(userId)
                .orElseThrow(() -> new ResourceNotFoundException("Сотрудник не найден по userId: " + userId));
        return documentRequestRepository.findByEmployeeId(employee.getId(), pageable)
                .map(documentRequestMapper::toResponse);
    }

    @Transactional(readOnly = true)
    public Page<DocumentRequestResponse> getAll(String status, Pageable pageable) {
        if (status != null) {
            return documentRequestRepository.findByStatus(DocumentRequestStatus.valueOf(status), pageable)
                    .map(documentRequestMapper::toResponse);
        }
        return documentRequestRepository.findAll(pageable).map(documentRequestMapper::toResponse);
    }

    @Transactional
    public DocumentRequestResponse updateStatus(UUID id, UpdateDocumentRequestStatusDto req, UUID actorId, String actorEmail, String actorRole) {
        DocumentRequest dr = findById(id);
        DocumentRequestStatus newStatus = DocumentRequestStatus.valueOf(req.status());

        validateTransition(dr.getStatus(), newStatus);

        dr.setStatus(newStatus);

        if (newStatus == DocumentRequestStatus.DONE) {
            if (req.fileUrl() != null && !req.fileUrl().isBlank()) {
                dr.setFileUrl(req.fileUrl());
            }
        }

        if (newStatus == DocumentRequestStatus.REJECTED) {
            dr.setRejectReason(req.rejectReason());
        }

        dr = documentRequestRepository.save(dr);
        log.info("Статус заявки обновлён: id={}, status={}, by={}", id, newStatus, actorId);

        activityLogProducer.log(
                ActivityAction.DOCUMENT_REQUEST_STATUS_UPDATED, ActivitySource.EMPLOYEE_SERVICE,
                actorId, actorEmail, actorRole,
                "DocumentRequest", id.toString(),
                "Document request status updated: " + newStatus);

        notificationService.createByEmployeeId(dr.getEmployee().getId(),
                "Статус заявки обновлён",
                "Ваша заявка на документ «" + dr.getDocumentType().name() + "» переведена в статус " + newStatus.name(),
                NotificationType.GENERAL, dr.getId(), "DOCUMENT_REQUEST");

        return documentRequestMapper.toResponse(dr);
    }

    @Transactional
    public DocumentRequestResponse sign(UUID id, UUID directorUserId, String actorEmail, String actorRole) {
        DocumentRequest dr = findById(id);

        if (dr.getStatus() != DocumentRequestStatus.DONE)
            throw new BadRequestException("Подписать можно только заявку в статусе DONE");

        dr.setSignedBy(directorUserId);
        dr.setSignedAt(LocalDateTime.now());
        dr = documentRequestRepository.save(dr);
        log.info("Документ подписан директором: id={}, directorUserId={}", id, directorUserId);

        activityLogProducer.log(
                ActivityAction.DOCUMENT_REQUEST_SIGNED, ActivitySource.EMPLOYEE_SERVICE,
                directorUserId, actorEmail, actorRole,
                "DocumentRequest", id.toString(),
                "Document request signed by director");

        notificationService.createByEmployeeId(dr.getEmployee().getId(),
                "Документ подписан",
                "Ваш документ «" + dr.getDocumentType().name() + "» подписан директором",
                NotificationType.GENERAL, dr.getId(), "DOCUMENT_REQUEST");

        return documentRequestMapper.toResponse(dr);
    }

    private void validateTransition(DocumentRequestStatus current, DocumentRequestStatus next) {
        boolean valid = switch (current) {
            case PENDING -> next == DocumentRequestStatus.IN_WORK || next == DocumentRequestStatus.REJECTED;
            case IN_WORK -> next == DocumentRequestStatus.DONE || next == DocumentRequestStatus.REJECTED;
            default -> false;
        };
        if (!valid)
            throw new BadRequestException("Недопустимый переход статуса: " + current + " → " + next);
    }

    private void notifyHr(Employee employee, DocumentRequest dr) {
        employeeRepository.findAll().stream()
                .filter(e -> {
                    String pos = e.getPositionName() != null ? e.getPositionName().toLowerCase() : "";
                    return pos.contains("hr") || pos.contains("admin");
                })
                .forEach(hr -> notificationService.createByEmployeeId(hr.getId(),
                        "Новая заявка на документ",
                        employee.getLastName() + " " + employee.getFirstName() + " запросил(а) документ: " + dr.getDocumentType().name(),
                        NotificationType.GENERAL, dr.getId(), "DOCUMENT_REQUEST"));
    }

    private DocumentRequest findById(UUID id) {
        return documentRequestRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Заявка на документ не найдена: " + id));
    }
}

